<h2>Add <?php echo $this->grabEntityLabel(); ?></h2>
<form>

<?php $attributes = $this->grabAttributes() ?>
<?php if($attributes): ?>
    <?php foreach($attributes as $attribute): ?>
           <div class="row"><?php echo $this->model('panels/kinds')->grab($attribute['kind'])->setData($attribute)->toHtml(); ?></div>
     <?php endforeach; ?>
<?php else: ?>
    <h2>There are no attributes assigned to this entity.</h2>
<?php endif; ?>


    <div class="row">
        <label>Attribute</label> <input type="text" name="attribute">
    </div>

    <button onclick="supa.doAction('addAttribute', $('form'), $('panel_modal_container')); return false;">Add</button>

</form>