<h2>Add <?php echo $this->grabEntityLabel(); ?></h2>
<form id="entity_add" method="post" action="/panels/eav/add">
<input type="hidden" name="entity" value="<?php echo $this->getDo('entity') ?>" />
<?php $attributes = $this->grabAttributes() ?>
<?php if($attributes): ?>
    <?php foreach($attributes as $attribute): ?>
           <div class="row"><?php echo $this->model('panels/kinds')->grab($attribute['kind'], $attribute); ?></div>
    <?php endforeach; ?>
    <div class="row options">
        <a class="panel-button" href="#" onclick="supa.doForm($('entity_add'), $('panelcontent')); return false">Add</a>
    </div>
<?php else: ?>
    <h2>Unable to comply: There are no attributes assigned to this entity.</h2>
<?php endif; ?>
</form>