<div class="panelModalContainer">
<h3><?php echo $this->grabEntityLabel(); ?> Collection</h3>

<?php $collection = $this->grabAttributes(false) ?>
<?php if($collection && $this->grabCollection()): ?>
    <table>
        <thead>
            <tr>
                <th></th>
                <?php foreach($collection as $val => $attr): ?>
                    <th><?php if(isset($attr['label'])) echo $attr['label']; else echo $attr['attribute']; ?></th>
                <?php endforeach ?>
                <td onclick="supa.doAction('panels/eav/add', {'entity':'<?php echo $this->getDo('entity') ?>'}, $('panelcontent'))">Add</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->grabCollection() as $item): ?>
            <tr onclick="supa.doAction('panels/eav/add', {'entity':'<?php echo $this->getDo('entity') ?>', id: '<?php echo $item['id'] ?>'}, $('panelcontent'))">
                <?php foreach($item as $att => $val): ?>
                    <td><span class="cell">
                    <?php if(isset($collection[$att]['kind'])): ?>
                        <?php echo substr(strip_tags($this->model('panels/kinds')->grab($collection[$att]['kind'], $val)), 0, 50) ?>
                    <?php else: ?>
                        <?php echo strip_tags($val); ?>
                    <?php endif ?>
                    </span></td>
                <?php endforeach ?>
                <td><a href="#" onclick="supa.doAction('panels/eav/collection', {'entity':'<?php echo $this->getDo('entity') ?>', 'perform': ['model','panels/eav','delete', '<?php echo $item['id'] ?>']}, $('panelcontent'))">Remove</a></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    </div>
<?php else: ?>
    <div id="container" class="text-center">
        <h3>Empty Collection <a herf="#" onclick="supa.doAction('panels/eav/add', {'entity':'<?php echo $this->getDo('entity') ?>'}, $('panelcontent'))"> New Item</a></h3>
    </div>

<?php endif; ?>
