<?php $entities = $this->getEntities() ?>
<ul class="navigation">
    <li><h2>Entities</h2></li>
    <?php if($entities): ?>
        <?php foreach($this->getEntities() as $entity => $data): ?>
            <?php if($this->grabEntityLabel($entity)): ?>
                <li onclick="supa.doAction('panels/eav/collection', {'entity':'<?php echo $entity ?>'}, $('panelcontent'))">
    <!--                --><?php //var_dump($data['label']) ?>
                    <?php echo $this->grabEntityLabel($entity) ?>
                </li>
            <?php endif ?>
        <?php endforeach ?>
    <?php else: ?>
        <div class="container text-center"><h3>No Entities Available</h3></div>
    <?php endif ?>
</ul>
<div id="panelcontent"  class="panel_content"></div>