<div class="post">
    <div class="heading"><?php if(is_string($this->getData('title'))):?><a href="<?php echo $this->getViewUrl() ?>"><?php echo $this->getData('title') ?></a><?php endif ?></div>

    <div class="commentcount"><?php if(is_string($this->getData('title'))):?><a class="blog-comment-count" href="#disqus_thread"></a><?php endif ?></div>
    <?php if($this->model('panels/users')->isLoggedIn()): ?>
        <a href="#" onclick="
            supa.doAction('panels/eav/entities', false, $('panel_modal_container'));
            supa.doAction('panels/eav/add', {'entity':'supa_modules_blog_models_posts', id: '<?php echo $this->getData('id') ?>'}, $('panelcontent'))
            ">Edit</a>
    <?php endif ?>


    <?php if(is_string($this->getData('byline'))): ?>
      By  <a class="byline" href="mailto: <?php if(is_string($this->getData('email'))) echo $this->getData('email'); ?>"><?php echo $this->getData('byline'); ?></a><br>
    <?php endif ?>
    <div class="content">
        <?php  if(is_string($this->getData('title'))) echo $this->getData('body'); ?>
    </div>


    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'supadev'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function () {
            var s = document.createElement('script'); s.async = true;
            s.type = 'text/javascript';
            s.src = '//' + disqus_shortname + '.disqus.com/count.js';
            (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
        }());
    </script>
</div>