<?php $user = $this->model('panels/users')->getUser(); ?>
<div id="panel">


    <div id="panel_modal_container" class="container"></div>
    <div id="close_button" onclick="$('panel_modal_container').innerHTML = ''" style="float: right">Close</div>


<span>Hello, <?php echo $user['email']; ?></span>

    <ul id="panel_menu">
        <li><a href="#" onclick="supa.doAction('panels/eav/entities', false, $('panel_modal_container'))">EAV</a></li>
        <li><a href="<?php echo $this->getUrl('panels/users/logout'); ?>">Logout</a></li>
    </ul>

</div>
