
<!doctype>
<html>
<head>
    <title>superterran dot com</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getConfig('path/themeurl'); ?>style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getConfig('path/themeurl'); ?>panels.css">

    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"></script>
    <script type="text/javascript" src="<?php echo $this->getConfig('path/themeurl'); ?>js/supa.js"></script>

</head>
<body><?php echo $this->html('panels'); ?>
<div id="box" class="container">
    <div id="header"><span class="logo">supeterran</span></div>

    <div id="content">
        <?php if($this->hasMessages()): ?>
        <div id="messages">
            <ul>
            <?php foreach($this->grabMessages() as $type => $msg): ?>
                    <li class = "<?php echo $type; ?>"><?php echo $msg; ?></li>
            <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>


        <?php echo $this->html('content'); ?>

    </div>

    <div id="right">

        <div class="avatar-wrapper">
            <img id="supa-avatar" src="https://www.google.com/s2/photos/profile/107618603073236931621">
            <div class="avatar-info">
                Doug Hatcher
            </div>
        </div>

        <ul>
            <li><label>Lives in</label> Charleston, SC</li>
            <li><label>From</label> Myrtle Beach, SC</li>
            <li><label>Works at</label> <a href="http://www.blueacorn.com/" target="new">Blue Acorn</a></li>
            <li><label>Hangs out on</label> <a href="https://plus.google.com/107618603073236931621/posts/p/pub">Google Plus</a>
                and <a href="http://www.reddit.com/user/superterran/">Reddit</a>
            </li>
        </ul>
    </div>

    <div id="footer"><div class="text">I hate all footer text</div></div>

    <div id="panels_login">
        <?php if(!$this->model('panels/users')->isLoggedIn()): ?>
            <a href="<?php echo $this->getUrl('panels/users/'); ?>">Panel</a></div>
        <?php else: ?>
            <a href="<?php echo $this->getUrl('panels/users/logout'); ?>">Logout</a></div>
        <?php endif; ?>
</div>


    <script type="text/javascript">
        var supa = new supa();
    </script>
</body>
</html>