
<!doctype>
<html>
<head>
    <title>superterran dot com</title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getConfig('path/themeurl'); ?>style.css">
</head>
<body>



<div id="box" class="container">
    <div id="header"><span class="logo">supeterran</span></div>

    <div id="content">

        <?php echo $this->html('content'); ?>

    </div>

    <div id="right">

        <div class="avatar-wrapper">
            <img id="supa-avatar" src="https://www.google.com/s2/photos/profile/107618603073236931621">
            <div class="avatar-info">
                Doug Hatcher
            </div>
        </div>

        <ul>
            <li><label>Lives in</label> Charleston, SC</li>
            <li><label>From</label> Myrtle Beach, SC</li>
            <li><label>Works at</label> <a href="http://www.blueacorn.com/" target="new">Blue Acorn</a></li>
            <li><label>Hangs out on</label> <a href="https://plus.google.com/107618603073236931621/posts/p/pub">Google Plus</a>
                and <a href="http://www.reddit.com/user/superterran/">Reddit</a>
            </li>
        </ul>
    </div>

    <div id="footer"><div class="text">I hate all footer text</div></div>

</div>

</body>
</html>