<?php if(is_string($this->getData())): ?>
    <?php echo $this->getData() ?>
<?php elseif(is_array($this->getData())): ?>


    <label><?php echo (string) $this->getData('label'); ?></label>

    <div id="wysihtml5-toolbar" style="display: none;">
        <a data-wysihtml5-command="bold">bold</a>
        <a data-wysihtml5-command="italic">italic</a>

        <!-- Some wysihtml5 commands require extra parameters -->
        <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red">red</a>
        <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green">green</a>
        <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue">blue</a>

        <!-- Some wysihtml5 commands like 'createLink' require extra paramaters specified by the user (eg. href) -->
        <a data-wysihtml5-command="createLink">insert link</a>
        <div data-wysihtml5-dialog="createLink" style="display: none;">
            <label>
                Link:
                <input data-wysihtml5-dialog-field="href" value="http://" class="text">
            </label>
            <a data-wysihtml5-dialog-action="save">OK</a> <a data-wysihtml5-dialog-action="cancel">Cancel</a>
        </div>
    </div>

    <textarea id="wysihtml5-textarea" class="<?php if(is_string($this->getData('kind'))) echo $this->getData('kind'); ?>" name="<?php echo $this->getData('attribute') ?>"
        onmousedown="if(!editor) { var editor = new wysihtml5.Editor('wysihtml5-textarea', { toolbar: 'wysihtml5-toolbar', parserRules:  wysihtml5ParserRules }) }"
    ><?php if(is_string($this->getData('value'))) echo $this->getData('value'); ?></textarea>
<?php endif ?>