<html>
<head>
    <title>:)</title>
    <style type="text/css">
        body { background-color: #111;text-align: center; margin: 0 auto}
        form {
            display: block;
            position: absolute;
            bottom: -100px;
        }
    </style>
</head>
<body>
<form method="post" action="<?php $this->getConfig('path/baseurl') ?>"><input type="password" name="curtain"><input type="submit"></form>
</body>
</html>