<!doctype>
<html>
<head>
    <title><?php echo $this->getConfig('app/name') ?></title>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getConfig('path/themeurl'); ?>style.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getConfig('path/themeurl'); ?>panels.css">

    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.0.0/prototype.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"></script>
    <script type="text/javascript" src="<?php echo $this->getConfig('path/themeurl'); ?>js/supa.js"></script>

</head>
<body><?php echo $this->html('panels'); ?>
<div id="box" class="container">
    <div id="header">
        <ul class="navigation">
            <li><a class="logo" href="<?php echo $this->getConfig('path/baseurl'); ?>"><?php echo $this->getConfig('app/name') ?></a></li>
            <li><a href="<?php echo $this->getUrl('blog'); ?>">Blog</a></li>
            <li><a href="#">Whatevea</a></li>
            <li><a href="#">Something Else</a></li>
        </ul>
    </div>


    <div id="most" class="container">
        <div id="content">
            <?php if ($this->hasMessages()): ?>
                <div id="messages">
                    <ul>
                        <?php foreach ($this->grabMessages() as $type => $msg): ?>
                            <li class="<?php echo $type; ?>"><?php echo $msg; ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>


            <?php echo $this->html('content'); ?>

        </div>

        <div id="right">

            <div class="avatar-wrapper">
                <img id="supa-avatar" src="<?php echo $this->getConfig('app/avatar') ?>">

                <div class="avatar-info">
                    <a href="mailto: <?php echo $this->getConfig('app/email') ?>"><?php echo $this->getConfig('app/author') ?></a>
                </div>
            </div>

            <ul>
                <li><label>Lives in</label> Charleston, SC</li>
                <li><label>From</label> Myrtle Beach, SC</li>
                <li><label>Works at</label> <a href="http://www.blueacorn.com/" target="new">Blue Acorn</a></li>
                <li><label>Hangs out on</label> <a href="https://plus.google.com/107618603073236931621/posts/p/pub">Google
                        Plus</a>
                    and <a href="http://www.reddit.com/user/superterran/">Reddit</a>
                </li>
            </ul>
        </div>

    </div>

    <div class="container">
        <div id="footer">
            <div class="text">Built with the <a href="https://github.com/superterran/supa" target="new">Supa Framework</a></div>
        </div>
    </div>


</div>

<script type="text/javascript">
    var supa = new supa();
    <?php echo $this->html('supa.js_after') ?>


    //        supa.doAction('panels/eav/entities', false, $('panel_modal_container'));
    //        supa.doAction('panels/eav/add', {'entity':'supa_modules_panels_models_users'}, $('panelcontent'))

</script>

</body>
</html>